name: Parameter Crawler

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/params.yaml"
      - "crawler/write_params.py"

env:
  PYTHONUNBUFFERED: true

jobs:
  j1:
    runs-on: ubuntu-latest
    container: python:slim
    steps:
      - run: apt-get update
      - run: apt-get -y install git
      - uses: actions/checkout@main
      - run: pip install -r crawler/requirements.txt
      - run: python crawler/write_params.py
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git config pull.ff only
          git add crawler/params.json
          git commit -a --allow-empty-message -m '' || exit 0
          git pull && git push