name: Traveling Salesman

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

env:
  GMAPSKEY: ${{ secrets.GMAPSKEY }}

jobs:
  j1:
    runs-on: ubuntu-latest
    container: python:slim
    steps:
      - run: apt-get update
      - run: apt-get -y install git
      - uses: actions/checkout@main
      - run: pip install -r traveling-salesman/requirements.txt
      - run: python traveling-salesman/solve-route.py
      - name: Add, Commit, Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add directions
          git commit -m 'add directions' || exit 0
          git add traveling-salesman/coord_list.json
          git add traveling-salesman/map.png
          git commit -m 'new best route' || exit 0
          git stash
          git pull --rebase
          git push
