name: Traveling Salesman

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

env:
  GMAPSKEY: ${{ secrets.GMAPSKEY }}

jobs:
  j1:
    runs-on: ubuntu-latest
    container: python:slim
    steps:
      - run: apt-get update
      - run: apt-get -y install git
      - uses: actions/checkout@main
      - run: pip install -r traveling-salesman/requirements.txt
      - run: python traveling-salesman/solve-route.py
      - name: Init git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase true
      - name: Commit and push if directions changed
        run: |-
          git add directions
          git commit -m 'add directions' || exit 0
          git pull && git push
      - name: Commit and push if it changed
        run: |-
          git add traveling-salesman/coord_list.json
          git commit -m 'new best route' || exit 0
          git pull && git push