name: Stadtrad

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/w1.yaml"
      - "crawler/*"

jobs:
  j1:
    runs-on: ubuntu-latest
    container: python:slim
    steps:
      - run: apt-get update
      - run: apt-get -y install git
      - uses: actions/checkout@main
      - run: mkdir -p data
      - run: mkdir -p svg
      - run: pip install -r crawler/requirements.txt
      - run: python crawler/run.py
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/*
          git add svg/*
          git commit -a --allow-empty-message -m '' || exit 0
          git pull && git push